build.fsx, paket.dependencies, paket.lock, src/msu.SmartMeterHome/paket.references
=> Remove FSharp:Formatting and Kestrel

.travis.yml, README.md, RELEASE_NOTES.md, appveyor.yml, build.fsx, src/Client/AssemblyInfo.fs, src/Server/AssemblyInfo.fs
don't merge until TravisCI succeeds
=> fixing travis and appveyor builds

NuGet.config, build.fsx, src/Server/Server.fsproj
with sdk rc4 released, no need of nuget dev feeds
i build and tested locally, and VSCode intellisense works for server.
=> use sdk 1.0.0-rc4

paket.dependencies, paket.lock, src/Client/App.fs, src/Client/Client.fsproj, src/Client/Messages.fs, src/Client/Style.fs, src/Client/Utils.fs, src/Client/css/site.css, src/Client/index.html, src/Client/pages/Login.fs, src/Client/pages/Menu.fs, src/Client/pages/WishList.fs, src/Server/Auth.fs, src/Server/Program.fs, src/Server/Server.fs, src/Server/Server.fsproj, src/Server/ServerTypes.fs, src/Server/Shared/Domain.fs, src/Server/TokenUtils.fs, src/Server/WishList.fs, src/Server/paket.references
=> Create a login page and add JSON Web Token

src/Client/Messages.fs, src/Client/pages/WishList.fs, src/Server/Server.fs, src/Server/WishList.fs
=> Post the WishList

src/Client/Messages.fs, src/Client/pages/WishList.fs, src/Server/Shared/Domain.fs, src/Server/WishList.fs
=> Add a form for new books

src/Client/App.fs, src/Client/pages/WishList.fs
- Using lazyView to keep UI stable when server responds with same WishList
=> Update UI before the round trip

src/Client/pages/WishList.fs, src/Server/Shared/Domain.fs, src/Server/WishList.fs
=> Put Validation into shared code and verify on client and server

README.md
this has no real diif. the PR is just a means to test Travis
=> Testing Travis build

README.md, RELEASE_NOTES.md, build.fsx
A web stack designed for developer happiness
=> Describing the Technology Stack

.travis.yml, appveyor.yml, build.fsx, paket.lock, src/Client/Client.fsproj, test/UITests/App.config, test/UITests/UITests.fsproj
=> Run Tests on CI

paket.dependencies, paket.lock, src/Client/App.fs, src/Client/Client.fsproj, src/Client/Messages.fs, src/Client/Style.fs, src/Client/pages/WishList.fs, src/Server/Auth.fs, src/Server/ServerTypes.fs, src/Server/Shared/Domain.fs, src/Server/WishList.fs
Update to JSON.NET latest with F# 4.1 fix
Various other fixes or cosmetic code changes, not all need be taken, I'm still trying to work out what feels most idiomatic
=> various fixes

src/Server/WishList.fs
/cc @dsyme 
@haf @Krzysztof-Cieslak where would I create a logger?
I mean I already have one in Server.fs (which comes down in the file list)
Is this a global variable?
=> Use suave logging

src/Client/pages/Menu.fs, test/UITests/Tests.fs
=> logout in test if logged in

README.md
=> Added alternative SDK install instructions to readme

build.fsx
If an other version of dotnet was already in PATH, first test failed, and full reinstall occured again and again.
Now checking in the temp folder where dotnet core is installed.
=> Improve install of dotnet core.

appveyor.yml, package.json
=> trying the version spec revert again

.vscode/settings.json
added vscode settings file to exclude for issue #84.
=> issue-84 added vscode config

src/Client/index.html
- Add a title
- Fix the meta http-equiv item
- Use tabs consistently
=> Fix minor html linting issues

build.sh
As per @dsyme [comment](https://github.com/fable-compiler/fable-suave-scaffold/commit/a297043dfa72c31a8c631d638a810940afcae8fe#commitcomment-21705496).
=> Remove unused function from bash script

src/Client/pages/WishList.fs
=> correctly disable add button if Link input is empty

.paket/paket.exe.config
no need for prereleases any more
=> Paket 5 is released

src/Client/App.fs
=> Improve readability by lifting nested pattern match.

.paket/Paket.Restore.targets, .paket/paket.exe.config, paket.dependencies, paket.lock, src/Client/Client.fsproj, src/Client/paket.references, src/Server/App.config, test/UITests/App.config, test/UITests/Runner.fs
depends on release of https://github.com/fsprojects/Paket/pull/2486
=> Use CLI magic

.gitignore, .vscode/launch.json, .vscode/tasks.json, README.md, package.json, src/Server/Server.fsproj, test/ServerTests/ServerTests.fsproj, yarn.lock
=> Add debugger config

.travis.yml, build.fsx, build.sh
otherwise we have to depend on every user setting it.
=> apply FrameworkPathOverride in the build script

README.md
Not sure where to put it. Please rearrange how you like and maybe add some more explanations what purpose some functions have. For example I am not really sure what the parsePage function really does and when it will be called.
=> added getting started section in readme

src/Client/pages/WishList.fs, src/Server/Shared/Domain.fs
ref https://github.com/SAFE-Stack/SAFE-BookStore/issues/168
=> disallow adding a duplicate book

src/Client/pages/Login.fs, src/Server/Shared/Domain.fs
ref https://github.com/SAFE-Stack/SAFE-BookStore/issues/168#issuecomment-331547810
this utilizes the same trick as https://github.com/SAFE-Stack/SAFE-BookStore/pull/108 (see https://github.com/SAFE-Stack/SAFE-BookStore/issues/107#issuecomment-301312224)
=> reset password box in view when changing username

src/Client/index.html
Urgs: TIL this ugliness. How can we make it use the real version that we have in package json
=> Update to react 16

paket.lock, src/Client/Client.fsproj
Fix the deprecate warnings when updating Fable.
=> Update Fable dependencies

README.md, src/Client/App.fs, src/Client/Client.fsproj, src/Client/pages/Home.fs
=> Decouple Page and App.Model, promote Home to a proper page

build.fsx, test/ServerTests/ServerTests.fsproj
=> use same cli for running the subtasks

src/Client/App.fs, src/Client/Client.fsproj, src/Client/ClientTypes.fs, src/Client/Style.fs, src/Client/pages/Login.fs, src/Client/pages/WishList.fs, src/Client/views/Menu.fs
I've played a little with the code to decouple the components as much as possible.
The user is now managed at the application level, as it was somehow awkward to access it from the menu component.
Menu is now simply a view without own state, as there is nothing to keep track of.
The login page state and messages are now only processed by the component itself, the embedding component get a notification about a successful login and can define how to react according to this fact.
Further work, not necessary in this PR, would be to separate the new book form as own component, similar to the login page.
Would love to hear your thoughts about the proposed changes.
=> Model variation

README.md
As discussed here https://github.com/SAFE-Stack/SAFE-BookStore/issues/244 and on Slack.
=> Update .NET Core SDK requirement.

README.md
Couple of quick documentation changes to make sure anyone following the steps gets it to work first time.
=> Bohdanszymanik patch docs

README.md
solves the problem described in #275
=> add workaround for deploying to Google AppEngine to docs

src/Client/pages/WishList.fs
Instead of directly including the html elements in the parent table :
* An array of elements is exposed to react with a key (Not a really good key but it'll do)
* Each element is a separate component that will appear as such in react dev tools
**Notes:**
* Sorry for the whitespace diff, I have it in auto cleanup in vscode, I can revert
* I'll PR later to use PureComponent instead of a stateless functional one (They aren't as optimized as they can be un-pure) as it give better perf and the immutability of F# record is a perfect match
* I didn't add a key to the `Book` type but I think it should have one as it's a best practice in react anyway (And it seem that the `AzureTable` server side is reduced to using a poor `RowKey` that will create problems) .
=> Make book list a list of components

src/Client/App.fs
=> add type annotation for loadUser() to prevent deserialize error

src/Client/App.fs, src/Client/pages/Login.fs, src/Client/pages/WishList.fs
I was showing this code to a Xamarin team member today and noticed a few places where comments or some textual cleanup might help in readability
=> minor formatting updates

build.fsx
Since V4 it's required to specify the mode
https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a
#313
=> Run dev server in webpack development mode

src/Server/Templates.fs
=> Put scripts into head

README.md, paket.dependencies, paket.lock, src/Server/paket.references, test/ServerTests/paket.references
@forki here you go.
it Fixes #334 . I have also updated Readme file.
=> Watcher tools removed. Read me updated for .Net Core SDK

README.md
fixes #352
Changing README Getting started instructions to reflect the current version of the code.
=> Bring README in sync with current version of the code

src/Client/webpack.config.js
See https://github.com/SAFE-Stack/SAFE-template/pull/133
=> fix symlinks

src/Server/Shared/ServerUrls.fs
There was an attribute missing.
=> Added missing literal attribute

.paket/Paket.Restore.targets, package.json, paket.dependencies, paket.lock, src/Client/App.fs, yarn.lock
=> with debugger

src/Client/webpack.config.js
=> Fix historyApiFallback setting in webpack.config.js

README.md
https://github.com/SAFE-Stack/SAFE-BookStore/issues/381
=> Update tutorial to match current code.
