SAFE-Stack/SAFE-BookStore

src/Server/Server.fsproj
Pin specific FSharp.NET.Sdk package version
because 1.0.0 is not yet supported by VSCode/Ionide/FSAC
The version range used was `1.0.0-beta-*` but anyway nuget resolved `1.0.0` instead of `1.0.0-beta-060000`
=> fix intellisense

src/Client/App.fs, src/Client/Messages.fs
Side effects with explicit failure modes are offloaded into commands.
Arguably, logging into console is also a side-effect, but normally you'd have a piece of model dedicated to conveying the problems to the user, so instead of logging into console this would just update the model.
=> offload side-effects into commands

build.fsx
This might be relevant for Linux as well, but I don't have access to a Linux installation of Mono and hence cannot test, so my changes only affect macOS. Fixes #62.
=> Don't rename chromedriver on macOS if it already exists

src/Server/Server.fsproj
Fixes #71.
Looks like it was a "bad" version of dotnet watch. Also see: https://github.com/aspnet/DotNetTools/issues/278
=> upgrade dotnet watch to 1.0.0, fix #71

src/Client/App.fs, src/Client/pages/Login.fs, src/Client/pages/WishList.fs
Several HTML elements were getting passed extra empty lists that were causing the client project to fail building.
** Someone else may already be addressing this, but I fixed it for my local development and thought it might be helpful if someone isn't working on it.  I can create an issue for this if that's more appropriate.**
=> Fixes client build issues

build.fsx
After a change I did to the FAKE script, the `Run` target wasn't running `dotnet restore` on the Server project.
=> Fix #98: Add InstallServer build target

Dockerfile
The current base docker image does not include version 1.1.1 of the .NET Core Runtime, which is required by netcoreapp1.1 by default. [apparently](http://stackoverflow.com/questions/42726198/dotnet-build-to-specific-framework-version).
Without this change you will receive the following error when trying to run the docker container:
```
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
- Check application dependencies and target a framework version installed at:
/usr/share/dotnet/shared/Microsoft.NETCore.App
- The following versions are installed:
1.1.0
1.0.3
- Alternatively, install the framework version '1.1.1'.
```
After updating the base image the app runs successfully.
I'm not sure if this change is appropriate, or if targeting a lower version of the …
=> netcoreapp1.1 projects depend on 1.1.1

src/Client/pages/WishList.fs
fixes https://github.com/fable-compiler/fable-suave-scaffold/issues/107
Was there a specific reason to use DefaultValue instead of Value?
A different fix would be to keep the previous Book as the current NewBook, that way the Dom <> Model would also stay consistent.
=> WishList: reset the three inputs after adding a book

Dockerfile, README.md, app.yaml, build.fsx, src/Client/webpack.config.js, src/Server/Program.fs, src/Server/Server.fs
This PR contains:
* Update to Dockerfile, 1.1.1 --> 1.1.2 (needs to be verified on Azure)
* Update to `Readme` on how to deploy to GCP
* Update to app and test to allow for different port based on env variable
* Configuration file that is used to deploy to GCP
=> add gcp deploy example

.gitignore, test/UITests/Tests.fs
As per commit, *If you remove Isaac's book from the wish list, the Canopy user login test fails, because it checks for Isaac.  While I agree that removing Isaac is a crime, the test should probably check for the logout option in the menu.  Changed to do this.*
=> Isolate user login test from changes in wish list.

README.md, build.fsx, test/ServerTests/Program.fs, test/ServerTests/ServerTests.fsproj, test/ServerTests/Tests.fs, test/ServerTests/paket.references
starter for #128 
what's working: live reload of test project and tests run.
I did not use Expecto Fake helpers, not sure if they would work with 'dotnet watch'
also I noticed at least once that 2 watching process deadlocked. Not sure what to do with it atm.
Signed-off-by: Alexander Prooks <aprooks@live.ru>
=> server tests starter with live reload

build.fsx, src/Server/Auth.fs
The UTF8.bytes function is hidden in Suave 2.2.0 and above, so we can't use it in the scaffold. Since the only functions that use it are exact duplicates of functions already in the Suave API, just remove them.
This will fix #145.
=> Ensure scaffold will still build with Suave 2.2.x

src/Client/App.fs
`withDebugger` must be the last command in the Elmish program chain. With this fix the time-travelling debugger tools work correctly.
=> Placed `withDebugger` in the correct position

src/Client/App.fs
This change is intended for better first time experience with HMR. Currently lazy views are not invalidated and reloaded with HMR unless you make changes to the state of the component or change the model of the component. This makes the first time experience with HMR really confusing.
=> Removed usage of lazyView2

build.fsx, test/UITests/Runner.fs
Looks like `phantomjs` is [deprecated](https://travis-ci.org/SAFE-Stack/SAFE-BookStore/builds/296451800#L4191):
`npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'`
This PR updates to the recommended `phantomjs-prebuilt` package.
=> use phantomjs-prebuilt

README.md
This updates the readme with additional instructions for mapping the Azure App Service's port 80 to the containers port 8085. While testing this I noticed that it didn't appear to be necessary to specify a startup file.
If you want, I can also add the instructions for setting up the app using the Azure CLI:
Create the resource group
`az group create --name <resource group name> --location "West US"`
Create the app service plan
`az appservice plan create --name <app service plan name> --resource-group <resource group name> --sku S1 --is-linux`
Create the app service itself
`az webapp create --resource-group <resource group name> --plan <app service plan name> --name <app service name> --deployment-container-image-name <container image name>`
Map the app service's port 80 to the containers …
=> Adds ACS port mapping instructions to address issue #235

build.fsx, package.json
Avoid things breaking up when other projects are building or being watched at the same time
=> Use a free port for fable daemon

src/Server/Auth.fs, src/Server/FableJson.fs, src/Server/Program.fs, src/Server/WishList.fs
Configured Giraffe's JSON serializer to use the FableConverter so that all JSON (de-)serialize methods use the Fable settings. As a result I could remove the custom JSON handlers for binding a model and writing a response.
=> Removed custom JSON handler

src/Client/index.html
Because the latest Bootstrap on CDN now is 4.0+, broke couple of things...
=> Change bootstrap.css to explicit 3.3.7

src/Server/Auth.fs, src/Server/Program.fs, src/Server/Server.fsproj, src/Server/ServerTypes.fs, src/Server/Shared/Domain.fs, src/Server/WebServer.fs, src/Server/WishList.fs
Simplified the Auth and WishList modules.
- Removed try-with in WishList functions by moving the error code to the error handler
- Removed try-with from login and return an error response straight away without throwing an exception first
- Changed the Auth useToken to requiresToken which is a handler now which validates the token and then passes the token to another http handler. This makes it possible to chain `Auth.requiresJwtToken` in the router so it is explicitly visible to any user at first sight which routes require authentication.
I have made a few changes which I think make the code a bit tidier and simpler, but it is very subjective, so please reject this PR or feel free to modify if you don't like it!
=> Little Refactor

build.fsx
When I execute `build run` I currently get an error and webpack isn't run:
```
dotnet fable --port free webpack-dev-server
dotnet watch msbuild /t:TestAndRun /p:DotNetHost=dotnet
Unrecognized command: --port. Use `dotnet fable --help` to see available options.
```
If I reorder the parameters to match the equivalent command in package.json it runs webpack as expected.
=> Reorder parameters to fable webpack-dev-server

yarn.lock
I noticed this because our firewall only has https://registry.npmjs.org whitelisted
=> yarn: use https for all packages

src/Client/Client.fsproj, src/Client/Shared.fs, src/Client/pages/Home.fs, src/Client/pages/Login.fs, src/Client/pages/NewBook.fs, src/Client/pages/WishList.fs, src/Client/views/Menu.fs, src/Client/views/Utils.fs, src/Server/Server.fsproj
This PR add a small `elmishView` helper to create views using `FunctionComponent.Of` with the new `equalsButFunctions` comparison now included in `Fable.React`.
With these changes, editing a book doesn't re-render the book list :
And adding a new book doesn't re-render all other books :
The menu is also never re-rendered except on login/logout.
=> Use React.memo

src/Client/pages/WishList.fs, src/Server/WebServer.fs
The posts for adding or removing books went to `/api/wishlist/{username}`, but resulted in 404 since `post "/api/wishlist/%s"` doesn't take format string parameters.
Since `WishList.postWishList` doesn't use user name from the URL parameter anyways, removing the user name feels the easiest fix.
=> Saving wishlist failed
